version: '3'

services:
  app_db:
    image: mysql:8.0
    container_name: app_db_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - ./auth_app_data:/var/lib/mysql

volumes:
  app_db_data: